### ISSUE TITLE
Installation: AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

### ISSUE THREAD

**Issue by tabacha** [okfde/fragdenstaat_de#54]
Moin,

Mein Versuch es nach der Readme auf einem Debian Jessie zu installieren, führt zu einer Fehlermeldung:

```
sven@merlin:~/fragdenstaat_de (master)$ pip install -e .
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 22, in <module>
    import requests, six
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from requests.packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 42, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
```

ich dachte mir, ich schau mir das mal an, ob ich mithelfen kann, ein paar Issuses abzubauen. Ich hab zwar noch keine Django Erfahrung, aber das ist bei mir eher Ansporn als Hindernis.

**Comment by tabacha** [comment]
Sorry, war zu doof zu sehen, dass da noch was in /usr/local/lib/python2.7 installiert war

**Comment by stefanw** [comment]
Ich habe auch gerade mal die `requirements.txt` aktualisiert, sollte jetzt alles neu und ggf. einfacher sein (kein lxml mehr z.B.).
